language: ruby
rvm:
    - "2.1.1"
env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
    - bundle exec jekyll build && bundle exec htmlproof --check-html ./_site
    - ./_script/check-stuypulse-capitalization.sh
    - ./_script/check-image-extensions.sh
